# Advanced networking and ingress test
nameOverride: "oxy-test-network"
fullnameOverride: "oxy-test-network"

app:
  image: "nginx"
  imageTag: "1.21-alpine"
  imagePullPolicy: "IfNotPresent"
  replicaCount: 2  # Multi-replica for networking tests

# Complex ingress configuration
ingress:
  enabled: true
  ingressClassName: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/$2"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/client-body-buffer-size: "128k"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "4k"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "8"
  
  path: "/api(/|$)(.*)"
  pathType: "Prefix"
  
  # Multiple hosts with different configurations
  hosts:
    - host: "api.oxy-test.local"
      paths:
        - path: "/api/v1"
          pathType: "Prefix"
        - path: "/api/v2"
          pathType: "Prefix"
        - path: "/health"
          pathType: "Exact"
        - path: "/metrics"
          pathType: "Exact"
    - host: "admin.oxy-test.local"  
      paths:
        - path: "/admin"
          pathType: "Prefix"
        - path: "/dashboard"
          pathType: "Prefix"
    - host: "oxy-test-network.local"
      paths:
        - path: "/"
          pathType: "Prefix"
  
  # TLS configuration
  tls:
    - hosts:
        - "api.oxy-test.local"
        - "admin.oxy-test.local"
      secretName: "oxy-api-tls"
    - hosts:
        - "oxy-test-network.local"
      secretName: "oxy-main-tls"

# Service configuration for networking tests
service:
  type: "ClusterIP"
  port: 80
  targetPort: 3000
  name: "oxy-network-service"

# Enable headless service for StatefulSet networking
headlessService:
  enabled: true

# Network-focused ConfigMap
configMap:
  enabled: true
  data:
    nginx.conf: |
      events {}
      http {
        upstream backend {
          server 127.0.0.1:3000;
        }
        
        server {
          listen 80;
          
          location / {
            return 200 'Network test OK';
            add_header Content-Type text/plain;
          }
          
          location /health {
            return 200 'healthy';
            add_header Content-Type text/plain;
          }
          
          location /api/v1 {
            return 200 'API v1 endpoint';
            add_header Content-Type text/plain;
          }
          
          location /api/v2 {
            return 200 'API v2 endpoint'; 
            add_header Content-Type text/plain;
          }
          
          location /admin {
            return 200 'Admin panel';
            add_header Content-Type text/plain;
          }
          
          location /metrics {
            return 200 'metrics endpoint';
            add_header Content-Type text/plain;
          }
        }
      }

# Environment for networking test
env:
  OXY_STATE_DIR: "/workspace/oxy_data"
  NETWORK_MODE: "advanced"
  CORS_ENABLED: "true"
  PROXY_TIMEOUT: "300"

# Enhanced probes for networking validation
livenessProbe:
  httpGet:
    path: "/health"
    port: 3000
    httpHeaders:
      - name: "X-Forwarded-Proto"
        value: "http"
      - name: "X-Forwarded-For"
        value: "127.0.0.1"
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: "/health"
    port: 3000
    httpHeaders:
      - name: "X-Health-Check"
        value: "readiness"
  initialDelaySeconds: 15
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 2

# Resources
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"

# Service account
serviceAccount:
  create: true
  name: "oxy-network-sa"
  annotations:
    "networking.test/multi-host": "true"

# Basic persistence
persistence:
  enabled: true
  size: "1Gi"
  accessMode: "ReadWriteOnce"
  mountPath: "/workspace"

# Security context
securityContext:
  fsGroup: 1000

# Disable non-networking features
gitSync:
  enabled: false

database:
  postgres:
    enabled: false

externalSecrets:
  create: false
  envSecretNames: []
  fileSecrets: []

extraInitContainers: []
extraSidecars: []