# Integration test with external secret
nameOverride: "oxy-test-external-secret"
fullnameOverride: "oxy-test-external-secret"

image:
  repository: nginx
  tag: "1.21-alpine"
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 80

# Enable external secret
externalSecret:
  enabled: true
  secretStore:
    name: "test-secret-store"
    kind: "SecretStore"
  target:
    name: "oxy-test-secret"
    creationPolicy: "Owner"
  data:
    - secretKey: "test-key"
      remoteRef:
        key: "test-remote-key"

# Disable external dependencies
database:
  postgres:
    enabled: false

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi