apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.app.name }}
    chart: {{ include "oxy-app.chart" . }}
    release: {{ .Release.Name }}
data:
  AWS_REGION: {{ .Values.env.AWS_REGION | quote }}
  OXY_STATE_DIR: {{ .Values.env.OXY_STATE_DIR | quote }}
  CLUSTER_NAME: {{ .Values.env.CLUSTER_NAME | quote }}
  ENVIRONMENT: {{ .Values.env.ENVIRONMENT | quote }}
