{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.app.name }}
    chart: {{ include "oxy-app.chart" . }}
    release: {{ .Release.Name }}
data:
  {{- /* Render explicit key/values only. toYaml handles empty maps. */}}
  {{- toYaml .Values.configMap.data | nindent 2 }}
{{- end }}
