{{- if .Values.ingress.enabled -}}
{{- $fullName := include "oxy-app.fullname" . -}}
{{- $svcName := default (printf "%s-service" .Values.app.name) .Values.service.name -}}
{{- $root := . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "oxy-app.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
{{ toYaml . | indent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName | quote }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
    {{- range $i, $host := .Values.ingress.hosts }}
    - host: {{ $host.host | quote }}
      http:
        paths:
          {{- if $host.paths }}
          {{- range $p := $host.paths }}
          - path: {{ $p.path | default $.Values.ingress.path | quote }}
            pathType: {{ $p.pathType | default $.Values.ingress.pathType }}
            backend:
              service:
                name: {{ $svcName }}
                port:
                  number: {{ $root.Values.service.port }}
          {{- end }}
          {{- else }}
          - path: {{ $.Values.ingress.path | quote }}
            pathType: {{ $.Values.ingress.pathType }}
            backend:
              service:
                name: {{ $svcName }}
                port:
                  number: {{ $root.Values.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
