apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    chart: {{ include "oxy-app.chart" . }}
    release: {{ .Release.Name }}
    version: v1
spec:
  serviceName: {{ .Release.Name }}-headless
  replicas: {{ .Values.app.replicaCount }}
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        version: v1
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- end }}
      securityContext:
        fsGroup: {{ .Values.securityContext.fsGroup }}

      # Init Containers
      initContainers:
      {{- if .Values.gitSync.enabled }}
        # Git Clone Init Container
        # One-time secure clone using kubernetes/git-sync. This creates a
        # linked copy at /workspace/current that the long-running git-sync
        # sidecar will keep up-to-date.
        - name: git-clone
          image: k8s.gcr.io/git-sync/git-sync:v4.4.3
          args:
            - --repo={{ .Values.gitSync.repository }}
            - --branch={{ .Values.gitSync.branch }}
            {{- $gitRoot := default (printf "%s/git" .Values.persistence.mountPath) .Values.gitSync.root }}
            {{- $gitLink := default (printf "%s/current" .Values.persistence.mountPath) .Values.gitSync.link }}
            - --root={{ $gitRoot }}
            - --link={{ $gitLink }}
            - --one-time=true
            - --depth=1
            - --ssh-key-file=/etc/git-secret/ssh
            - --ssh-known-hosts-file=/etc/git-secret/known_hosts
            - --max-failures=5
            - --verbose=1
          volumeMounts:
            - name: workspace
              mountPath: {{ .Values.persistence.mountPath }}
            - name: git-ssh
              mountPath: /etc/git-secret
              readOnly: true
      {{- end }}

      # Main Application Container
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.app.image }}:{{ default .Chart.AppVersion .Values.app.imageTag }}"
          command:
            - sh
            - -c
            - |
              exec oxy serve{{- if not .Values.gitSync.enabled }} --readonly{{- end }}
          {{- if .Values.gitSync.enabled }}
          {{- $gitLink := default (printf "%s/current" .Values.persistence.mountPath) .Values.gitSync.link }}
          workingDir: {{ $gitLink }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.app.port }}
              protocol: TCP
              name: traffic-port

          # Environment Variables
          env:
            # State Directory Configuration
            {{- if and .Values.env.OXY_STATE_DIR (ne .Values.env.OXY_STATE_DIR "") }}
            - name: OXY_STATE_DIR
              value: "{{ .Values.env.OXY_STATE_DIR }}"
            {{- else }}
            - name: OXY_STATE_DIR
              value: "{{ printf "%s/%s" .Values.persistence.mountPath .Values.persistence.folder }}"
            {{- end }}

            # Database URL Configuration
            # Preference order (sqlite fallback intentionally omitted):
            # 1) Explicit value provided by caller via values.env.OXY_DATABASE_URL
            # 2) Explicit external.connectionString or external fields
            # 3) Postgres subchart connection (if user enabled it manually)
            # If none are provided, OXY_DATABASE_URL will not be set
            {{- if and .Values.env.OXY_DATABASE_URL (ne .Values.env.OXY_DATABASE_URL "") }}
            - name: OXY_DATABASE_URL
              value: "{{ .Values.env.OXY_DATABASE_URL }}"
            {{- else if and .Values.database.external.enabled (ne .Values.database.external.connectionString "") }}
            - name: OXY_DATABASE_URL
              value: "{{ .Values.database.external.connectionString }}"
            {{- else if .Values.database.external.enabled }}
            - name: OXY_DATABASE_URL
              value: "postgresql://{{ .Values.database.external.user }}:{{ .Values.database.external.password }}@{{ .Values.database.external.host }}:{{ .Values.database.external.port }}/{{ .Values.database.external.database }}"
            {{- else if .Values.database.postgres.enabled }}
            - name: OXY_DATABASE_URL
              value: "postgresql://{{ .Values.database.postgres.postgresqlUsername }}:{{ .Values.database.postgres.postgresqlPassword }}@{{ include "oxy-app.fullname" . }}-postgresql.{{ .Release.Namespace }}.svc.cluster.local:5432/{{ .Values.database.postgres.postgresqlDatabase }}"
            {{- end }}

          # ConfigMap / Secret Environment Variables
          {{- if or .Values.configMap.enabled (gt (len .Values.externalSecrets.envSecretNames) 0) }}
          envFrom:
            {{- if .Values.configMap.enabled }}
            - configMapRef:
                name: {{ .Release.Name }}-config
            {{- end }}
            {{- range $idx, $s := .Values.externalSecrets.envSecretNames }}
            - secretRef:
                name: {{ $s | quote }}
            {{- end }}
          {{- end }}

          # Resource Limits and Requests
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          # Volume Mounts
          volumeMounts:
            - name: workspace
              mountPath: {{ .Values.persistence.mountPath }}
            {{- /* Mount environment secrets */}}
            {{- range $idx, $s := .Values.externalSecrets.envSecretNames }}
            - name: env-secret-{{ $idx }}
              mountPath: /secrets/env/{{ $s }}
              readOnly: true
            {{- end }}
            {{- /* Mount file secrets */}}
            {{- range $idx, $f := .Values.externalSecrets.fileSecrets }}
            - name: file-secret-{{ $idx }}
              mountPath: /secrets/files/{{ $f.name }}
              readOnly: true
            {{- end }}

          # Health Checks
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}

      # Volume Definitions
      volumes:
        {{- if .Values.gitSync.enabled }}
        - name: git-ssh
          secret:
            secretName: {{ .Values.gitSync.sshSecretName }}
            optional: false
        {{- end }}
        {{- /* Environment secret volumes */}}
        {{- range $idx, $s := .Values.externalSecrets.envSecretNames }}
        - name: env-secret-{{ $idx }}
          secret:
            secretName: {{ $s | quote }}
            optional: true
        {{- end }}
        {{- /* File secret volumes */}}
        {{- range $idx, $f := .Values.externalSecrets.fileSecrets }}
        - name: file-secret-{{ $idx }}
          secret:
            secretName: {{ $f.name | quote }}
            optional: true
        {{- end }}

      # Node Selection and Tolerations
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

  # Persistent Volume Claim Templates
  volumeClaimTemplates:
    - metadata:
        name: workspace
        annotations:
          {{- toYaml .Values.persistence.annotations | nindent 10 }}
        labels:
          {{- toYaml .Values.persistence.labels | nindent 10 }}
      spec:
        accessModes:
          - "{{ .Values.persistence.accessMode }}"
        {{- if .Values.persistence.storageClassName }}
        storageClassName: {{ .Values.persistence.storageClassName }}
        {{- end }}
        {{- if .Values.persistence.volumeMode }}
        volumeMode: {{ .Values.persistence.volumeMode }}
        {{- end }}
        {{- if .Values.persistence.selector }}
        selector:
          {{- toYaml .Values.persistence.selector | nindent 10 }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}