name: Helm lint & test

on:
  push:
    paths:
      - "charts/**"
      - ".github/workflows/**"
  pull_request:
    paths:
      - "charts/**"
      - ".github/workflows/**"

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4
        with:
          version: "3.12.0"

      - name: Show Helm version
        run: helm version

      - name: Make scripts executable
        run: echo "Skipping repository scripts; using inline helm commands"

      - name: Install helm-unittest plugin
        run: |
          helm plugin install https://github.com/quintush/helm-unittest || true

      - name: Find charts
        id: find_charts
        run: |
          # find top-level chart directories under charts/
          find charts -maxdepth 2 -type f -name Chart.yaml -print | sed 's:/Chart.yaml::' > chart_dirs.txt
          cat chart_dirs.txt

      - name: Run ct lint (chart-testing)
        uses: helm/chart-testing-action@v2
        with:
          command: lint
          config: |
            chart-dirs:
              - charts
            exclude:
              - charts/**/tests/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run helm-unittest for charts with tests
        run: |
          while read -r chartdir; do
            if [ -d "$chartdir/tests" ]; then
              echo "Running helm-unittest for $chartdir"
              helm unittest "$chartdir" || exit 1
            else
              echo "No tests for $chartdir"
            fi
          done < chart_dirs.txt
