name: Publish Helm charts to gh-pages

on:
  push:
    branches:
      - main


jobs:
  publish:
    permissions:
      contents: write # to push chart release and create a release (helm/chart-releaser-action)
      packages: write # needed for ghcr access
    name: Package & Publish Helm charts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Create GitHub App Token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.ARGO_APP_ID }}
          private-key: ${{ secrets.ARGO_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Configure Git
        run: |
          git config --global user.email "153820223+oxyhelper[bot]@users.noreply.github.com"
          git config --global user.name "oxyhelper[bot]"

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0

      - name: Add dependency chart repos
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: "${{ steps.app-token.outputs.token }}"
          CR_SKIP_EXISTING: "true"
        with:
          charts_dir: charts
          config: cr.yaml

      - name: Login to GHCR
        uses: docker/login-action@v3 # v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ steps.app-token.outputs.token }}

      - name: Push charts to GHCR
        run: |
          shopt -s nullglob
          for pkg in .cr-release-packages/*.tgz; do
            if [ -z "${pkg:-}" ]; then
              break
            fi
            helm push "${pkg}" "oci://ghcr.io/${GITHUB_REPOSITORY_OWNER}/helm-charts"
          done